CREATE TABLE [dbo].[DRBILL_states_combined_cleanedofSoMuchEvil_BAKJF_24SEP2021]
(
[id] [int] NOT NULL,
[Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_Address1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_Address2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_Zip] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_County] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office_Fax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cell_Phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[License_Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[License_Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original_Issue_Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expiration_Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Association] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isCustomer] [bit] NULL,
[isCordialMRK] [bit] NULL,
[isCordialInvalid] [bit] NULL,
[isCordialUnsubHOM] [bit] NULL,
[isCordialValidAndSubscribed] [bit] NULL,
[company_short_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sourceList] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GBSCompanyID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]