CREATE TABLE [dbo].[SN_ImposerExport_Label]
(
[batchTimestamp] [datetime] NOT NULL,
[PKID] [int] NOT NULL,
[orderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderID] [int] NULL,
[opid] [int] NULL,
[orderDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderPrintedDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batchImpo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Surname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Suburb] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_PostCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productQuantity] [int] NULL,
[frontPdf] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[backPdf] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[size] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[signXofX] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bottomLabel1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bottomLabel2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[squareLabel] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[circleLabel] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProducts] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fastTrackResubmit] [bit] NULL
) ON [PRIMARY]