CREATE TABLE [dbo].[tblStore_Prefs]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[storeLocale] [int] NULL,
[formatCurrReplace] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currencySuffix] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preOrder_Display] [bit] NOT NULL,
[preOrder_Order] [bit] NOT NULL,
[displayCategoryImages] [bit] NOT NULL,
[displayCategoryDescription] [bit] NOT NULL,
[maxProductsReturned] [int] NULL,
[storeClosed] [bit] NOT NULL,
[storeClosedMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeInitials] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeBusinessDetails] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeStreet] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeSuburb] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeState] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storePostCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeCountry] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeFax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeEmail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeWebsite] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storePageTitle] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sessionTimeout] [int] NULL,
[lastUpdate] [datetime] NULL,
[cvMajor] [int] NULL,
[cvMinor] [int] NULL,
[cvBuild] [int] NULL,
[salt] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homeDisplayTopProducts] [bit] NOT NULL,
[homeDisplayNoProducts] [int] NULL,
[displayEmailFriend] [bit] NOT NULL,
[sn] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingWeightMetric] [bit] NOT NULL,
[pricesIncTax] [bit] NOT NULL,
[reminderLastSend] [datetime] NULL,
[reminderAuto] [bit] NOT NULL,
[eCartHTML] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeLogo] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblStore_Prefs] ADD CONSTRAINT [PK_tblStore_Prefs] PRIMARY KEY CLUSTERED  ([ID]) WITH (FILLFACTOR=90) ON [PRIMARY]