CREATE TABLE [dbo].[tblProducts_Bounce2]
(
[productID] [int] NOT NULL IDENTITY(1, 1),
[productOnline] [bit] NOT NULL,
[canOrder] [bit] NOT NULL,
[productCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productIndex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extendedDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[warranty] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[costPrice] [money] NULL,
[retailPrice] [money] NULL,
[salePrice] [money] NULL,
[no_shipping] [bit] NULL,
[downloadable] [int] NULL,
[downloadableFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[downloadableShipped] [bit] NOT NULL,
[downloadableDaysValid] [int] NULL,
[dateAvailable] [smalldatetime] NULL,
[onOrder] [int] NOT NULL,
[stock_AutoReduce] [bit] NOT NULL,
[stock_LowNoOrder] [bit] NOT NULL,
[stock_LowLevel] [int] NULL,
[weight] [float] NULL,
[dimensionW] [float] NULL,
[dimensionH] [float] NULL,
[dimensionD] [float] NULL,
[manufacturer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[supplierID] [int] NULL,
[imageThumbnail] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image1] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image1Large] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image2] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image2Large] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image3] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image3Large] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[placedInCartCount] [int] NULL,
[numberSoldCount] [int] NULL,
[viewCount] [int] NULL,
[soldValue] [money] NULL,
[status_mode] [int] NULL,
[status_auto_Low] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_auto_inStock] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_man] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxApplies] [bit] NOT NULL,
[displayOrderGroup] [int] NULL,
[productType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventoryCount] [int] NULL,
[inventoryCountDate] [datetime] NOT NULL,
[parentProductID] [int] NULL,
[productMultiplier] [int] NULL,
[productCompany] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numUnits] [int] NULL,
[stock_Level] [int] NULL,
[INV_WIPHOLD_PHYS] [int] NULL,
[INV_ADJ] [int] NULL,
[INV_PS] [int] NULL,
[INV_WIPHOLD] [int] NULL,
[INV_AVAIL] [int] NULL,
[INV_ONHOLD_SOLO] [int] NULL,
[INV_WIP_SOLO] [int] NULL,
[artBackgroundImageName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]