CREATE TABLE [dbo].[tblEOM_Bouncer]
(
[storeID] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NO MATCH] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[transactionDateTime] [smalldatetime] NULL,
[orderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_zip] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[goToState] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subTotal] [money] NULL,
[shipTotal] [money] NULL,
[taxTotal] [money] NULL,
[taxDescription] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[amount] [money] NULL,
[calcOrderTotal] [money] NULL,
[calcTransTotal] [money] NULL,
[displayPaymentStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seqNo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cardType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cardHolderNo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[expDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[authCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entryMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[termOPID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[transactionType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerID] [int] NULL,
[billingName] [nvarchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_Company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_Suburb] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_postCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingName] [nvarchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Suburb] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_postCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original_postCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batchNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batchClose] [date] NULL,
[customData] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderID] [int] NOT NULL,
[rowID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rowSource] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billingReference] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calcProducts] [money] NULL,
[calcOPPO] [money] NULL,
[calcVouchers] [money] NULL,
[calcCredits] [money] NULL,
[taxRate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxCity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]