CREATE TABLE [dbo].[BregalMain03]
(
[JobNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalQTY] [int] NULL,
[Facility] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paper] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Proof] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Front Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Back Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coating] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wrap &amp; Band] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mailing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NCOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Use Own Permit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hole Drilling] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Folding] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dedupe] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Page Count] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Binding] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coating Cover] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coating Text] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cover Paper] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Digital Catalog] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Version] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]