CREATE TABLE [dbo].[tempJF_badgeSuccess29JUN2020]
(
[opid] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tempJF_badgeSuccess29JUN2020] ADD CONSTRAINT [PK_tempJF_badgeSuccess29JUN2020] PRIMARY KEY CLUSTERED  ([opid]) ON [PRIMARY]