CREATE TABLE [dbo].[tblA1_CC]
(
[orderID] [int] NOT NULL,
[orderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[shipState] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GBSZone] [int] NULL,
[rdi] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPSRural] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_rural] DEFAULT ((0)),
[returnCode] [int] NULL,
[CACP] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_CACP] DEFAULT ((0)),
[CACP_QTY] [int] NOT NULL CONSTRAINT [DF_tblA1_CC_CACP_QTY] DEFAULT ((0)),
[DK] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_DK] DEFAULT ((0)),
[DK_QTY] [int] NOT NULL CONSTRAINT [DF_tblA1_CC_DK_QTY] DEFAULT ((0)),
[ES] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_ES] DEFAULT ((0)),
[ES_QTY] [int] NOT NULL CONSTRAINT [DF_tblA1_CC_ES_QTY] DEFAULT ((0)),
[QS] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_QS_STOCK] DEFAULT ((0)),
[QS_QTY] [int] NOT NULL CONSTRAINT [DF_tblA1_CC_QS_Stock_QTY] DEFAULT ((0)),
[EV07] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_EV07] DEFAULT ((0)),
[EV07_QTY] [int] NOT NULL CONSTRAINT [DF_tblA1_CC_EV07_QTY] DEFAULT ((0)),
[EV10] [bit] NOT NULL CONSTRAINT [DF_tblA1_CC_EV10] DEFAULT ((0)),
[EV10_QTY] [int] NOT NULL CONSTRAINT [DF_tblA1_CC_EV10_QTY] DEFAULT ((0)),
[cnCACP] [int] NULL,
[cnCACP_DK] [int] NULL,
[cnCACP_ES] [int] NULL,
[cnCACP_DK_ES] [int] NULL,
[cnCACP_EV07] [int] NULL,
[cnCACP_EV07_DK] [int] NULL,
[cnCACP_EV07_ES] [int] NULL,
[cnCACP_EV07_DK_ES] [int] NULL,
[cnCACP_EV10] [int] NULL,
[cnCACP_EV10_DK] [int] NULL,
[cnCACP_EV10_ES] [int] NULL,
[cnCACP_EV10_DK_ES] [int] NULL,
[cnQS] [int] NULL,
[cnQS_DK] [int] NULL,
[cnQS_ES] [int] NULL,
[cnQS_DK_ES] [int] NULL,
[cnQS_EV07] [int] NULL,
[cnQS_EV07_DK] [int] NULL,
[cnQS_EV07_ES] [int] NULL,
[cnQS_EV07_DK_ES] [int] NULL,
[cnQS_EV10] [int] NULL,
[cnQS_EV10_DK] [int] NULL,
[cnQS_EV10_ES] [int] NULL,
[cnQS_EV10_DK_ES] [int] NULL,
[cnAll_Targeted] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblA1_CC] ADD CONSTRAINT [PK_tblA1_CC_1] PRIMARY KEY CLUSTERED  ([orderID]) ON [PRIMARY]