CREATE TABLE [dbo].[tempNC_tickets]
(
[PKID] [decimal] (18, 0) NOT NULL,
[orderNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OPID] [decimal] (18, 0) NOT NULL,
[outputName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[surface1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[surface2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[surface3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[barcode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[auxiliaryText] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quantity] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pUnitCount] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCount] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipColor] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipsWith] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipsWithAlt] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[resubmit] [bit] NULL,
[expedite] [bit] NULL,
[shipLine1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipLine2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipLine3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipLine4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipLine5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customProducts] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fasTrakProducts] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProduct1] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProduct2] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProduct3] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProduct4] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProduct5] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProduct6] [varchar] (130) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeLogo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]