CREATE TABLE [dbo].[tblEndicia_PrintHistory_Stage]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Print Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount Paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adj  Amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quoted Amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Recipient] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Origin Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tracking #] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Delivered] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carrier] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class Service] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Extra Services] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Insured Value] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Insurance ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Weight] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refund Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Printed Message] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refund Request Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refund Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refund Requested] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inputFileName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dateCreated] [datetime] NOT NULL CONSTRAINT [DF_tblEndicia_PrintHistory_Stage_dateCreated] DEFAULT (getdate())
) ON [PRIMARY]