CREATE TABLE [dbo].[tblArtMerge]
(
[arb] [int] NOT NULL IDENTITY(1, 1),
[pkid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productQuantity] [int] NULL,
[bkgnd_new] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[projectName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yourName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yourCompany] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[logo1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[logo2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[photo1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[photo2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overflow1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overflow2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overflow3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overflow4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overflow5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bkgnd_old] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[profsymbol1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[profsymbol2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[profsymbol3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enterdate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[input8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[marketCenterName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[projectDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[csz] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yourName2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[streetAddress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordersProductsID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sequencer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oppo_PKID] [int] NULL,
[previousJobArt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[previousJobInfo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[artInstructions] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [PKID_IX] ON [dbo].[tblArtMerge] ([pkid]) WITH (FILLFACTOR=90) ON [PRIMARY]