CREATE TABLE [dbo].[tblProductsNOTIMES]
(
[productID] [int] NOT NULL,
[productOnline] [bit] NOT NULL,
[canOrder] [bit] NOT NULL,
[productCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentProductCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCodeSuffix] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productIndex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productHeader] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[extendedDescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[warranty] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[costPrice] [money] NULL,
[retailPrice] [money] NULL,
[salePrice] [money] NULL,
[promoPrice] [money] NULL,
[no_shipping] [bit] NULL,
[downloadable] [int] NULL,
[downloadableFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[downloadableShipped] [bit] NOT NULL,
[downloadableDaysValid] [int] NULL,
[dateAvailable] [datetime] NULL,
[onOrder] [int] NULL,
[onHold] [int] NULL,
[stock_Level] [int] NULL,
[stock_AutoReduce] [bit] NOT NULL,
[stock_LowNoOrder] [bit] NOT NULL,
[stock_LowLevel] [int] NULL,
[weight] [float] NULL,
[dimensionW] [float] NULL,
[dimensionH] [float] NULL,
[dimensionD] [float] NULL,
[manufacturer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[supplierID] [int] NULL,
[imageThumbnail] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image1] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image1Large] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image2] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image2Large] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image3] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image3Large] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[imageInfoLines] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[popupWidth] [int] NULL,
[popupHeight] [int] NULL,
[placedInCartCount] [int] NULL,
[numberSoldCount] [int] NULL,
[viewCount] [int] NULL,
[soldValue] [money] NULL,
[status_mode] [int] NULL,
[status_auto_Low] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_auto_inStock] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_man] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxApplies] [bit] NOT NULL,
[displayOrderGroup] [int] NULL,
[itemType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventoryCount] [int] NULL,
[inventoryCountDate] [datetime] NULL,
[parentProductID] [int] NULL,
[productMultiplier] [int] NULL,
[productCompany] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productSize] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productThickness] [int] NULL,
[productTheme] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productTheme2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtyPerCarton] [int] NULL,
[minimumOrderQty] [int] NULL,
[itemStyle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[packType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productSport] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productIndustry] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCategory] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCategoryLink] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productLanguage] [int] NULL,
[stockStatus] [int] NOT NULL,
[possibleUses] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oneOunce] [bit] NOT NULL,
[otherQtyID] [int] NULL,
[noDisplayOtherQty] [int] NULL,
[freeShippingWeight] [bit] NULL,
[freeShipping] [bit] NULL,
[noQtyDiscount] [bit] NULL,
[customPriceChart] [bit] NULL,
[customQtyBox] [bit] NULL,
[customHeader] [bit] NULL,
[noCartQtyBox] [bit] NULL,
[infoPlacement] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productYear] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[saleText] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[saleExpDate] [datetime] NULL
) ON [PRIMARY]