CREATE TABLE [dbo].[tblWeight]
(
[WEIGHT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND5] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND6] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND7] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND8] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRND9] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY5] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY6] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY7] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY8] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3DAY9] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY5] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY6] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY7] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY8] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2DAY9] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT5] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT6] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT7] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT8] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT9] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]