CREATE TABLE [dbo].[ImposerNCTicketsLog]
(
[PKID] [int] NOT NULL IDENTITY(1, 1),
[OrderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrderID] [int] NULL,
[OppoPKID] [int] NULL,
[OPID] [int] NOT NULL,
[OutputName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Surface1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Surface2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Surface3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Surface4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Barcode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuxiliaryText] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quantity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pUnitCount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductCount] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipColor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipsWith] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipsWithAlt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipZone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Resubmit] [bit] NOT NULL CONSTRAINT [DF_ImposerNCTicketsLog_Resubmit] DEFAULT ((0)),
[Expedite] [bit] NOT NULL CONSTRAINT [DF_ImposerNCTicketsLog_Expedite] DEFAULT ((0)),
[ShipLine1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipLine2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipLine3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipLine4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipLine5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomProducts] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fasTrakProducts] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockProduct1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockProduct2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockProduct3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockProduct4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockProduct5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockProduct6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupID] [int] NULL,
[StoreLogo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UV] [int] NULL,
[Aux1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux9] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux12] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux13] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux14] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux15] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux16] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux17] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aux20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsertedOn] [datetime2] NOT NULL CONSTRAINT [DF_ImposerNCTicketsLog_InsertedOn] DEFAULT (getdate()),
[ImpositionID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ImposerNCTicketsLog] ADD CONSTRAINT [PK_ImposerNCTicketsLog] PRIMARY KEY CLUSTERED  ([PKID]) ON [PRIMARY]