CREATE TABLE [dbo].[BregalJobToOptions]
(
[JobNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[xOption] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paper] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Proof] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Front Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Back Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coating] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wrap &amp; Band] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mailing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NCOA] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Use Own Permit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hole Drilling] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Folding] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dedupe] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Page Count] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Binding] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coating Cover] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coating Text] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cover Paper] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Digital Catalog] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Version] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organ] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Printing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Finishing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Design Cost] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ink] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kit Fulfillment] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Packaging] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Envelope Size] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Multi-Version Pricing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Envelope Stock] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Reply Card] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Grouping Job] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personalized] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Card Slits] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customization] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Material] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Paper Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Submit File Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orientation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Press Check] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Project Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ English] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Design Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Plates] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Punching] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quantity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Envelope] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Envelope Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Envelope Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Piece Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Graphic Design] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sheets in Pad] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Method] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tabbing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pad Backing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fulfillment] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Use Customer Permit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Variable Printing] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pole Pockets] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bindery] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inks] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job Quantity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flat Size] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-20180917-153715] ON [dbo].[BregalJobToOptions] ([JobNumber]) ON [PRIMARY]