CREATE TABLE [dbo].[tempJF_NCCAllTimeOrders]
(
[orderNo] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderDate] [datetime] NULL,
[orderYear] [int] NULL,
[orderTotal] [money] NULL,
[TransactionTotal] [money] NULL,
[orderStatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentStatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productPrice] [money] NULL,
[productQuantity] [int] NULL,
[billing_Company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_Street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_Street2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_Suburb] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_State] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_postCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingCustomerName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Street2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Suburb] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_State] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_postCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerID] [int] NOT NULL,
[orderID] [int] NOT NULL,
[productID] [int] NULL,
[ordersProductsID] [int] NOT NULL,
[prevCustomer] [int] NOT NULL,
[causeSelected] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]