CREATE TABLE [dbo].[tblGroupOrders]
(
[uniqueID] [int] NOT NULL IDENTITY(500000, 1),
[coordinator] [int] NULL,
[firstName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[officePhone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cellPhone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numAgents] [int] NULL,
[jobTitle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[otherJob] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numLocations] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[insertDate] [datetime] NULL,
[status] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_tblGroupOrders_status] DEFAULT ('New'),
[couponNum] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_tblGroupOrders_couponNum] DEFAULT (0),
[couponSent] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_tblGroupOrders_couponSent] DEFAULT ('No'),
[couponDate] [datetime] NULL,
[couponExpirey] [datetime] NULL,
[couponStatus] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_tblGroupOrders_couponStatus] DEFAULT ('No Coupon Assigned'),
[brokerOwnerCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[goForPrint] [bit] NULL,
[goPrinted] [bit] NULL,
[printDate] [datetime] NULL,
[tickler] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[expiryWarningSent] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deletex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_tblGroupOrders_deletex] DEFAULT (0)
) ON [PRIMARY]