CREATE TABLE [dbo].[tblCustomers_PSCID2]
(
[customerID] [int] NOT NULL IDENTITY(1, 1),
[firstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[surname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[street2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suburb] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[website] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[login] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerPassword] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[newsletter] [bit] NULL,
[membershipType] [int] NULL,
[membershipNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coordID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CID] [int] NULL,
[shipping] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[legit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[beforeCutoff] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sUserDefined] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderNoJF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[typeJF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSCID] [int] NULL,
[PSCGPCOORDID] [int] NULL,
[fullname] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLANNER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]