CREATE TABLE [dbo].[tblStore_Checkout]
(
[ID] [int] NULL,
[orderPrefix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[enableSSL] [bit] NOT NULL,
[enableAdminSSL] [bit] NOT NULL,
[adminSSLAll] [bit] NOT NULL,
[myAccountSSL] [bit] NOT NULL,
[websiteURL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[adminURL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sslDomain] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdminSslDomain] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[storeFullCardNumbers] [bit] NOT NULL,
[encryptCardNumbers] [bit] NOT NULL,
[partialCardNumberAfterSuccessfulOrder] [bit] NOT NULL,
[minOrderLimit] [money] NULL,
[maxOrderLimit] [money] NULL,
[minGiftVoucherAmount] [money] NULL,
[ccProcessRealTime] [bit] NOT NULL,
[ccProcessAtCheckout] [bit] NOT NULL,
[ccProcessInStockOnly] [bit] NOT NULL,
[ccRequestCCV] [bit] NOT NULL,
[homeTaxCountryRule] [int] NULL,
[enableCustomerLookup] [bit] NOT NULL,
[enableNewsletter] [bit] NOT NULL,
[restrictionAllow] [bit] NOT NULL,
[hashPasswords] [bit] NOT NULL,
[stateNotRequired] [bit] NOT NULL,
[enableVouchers] [bit] NOT NULL
) ON [PRIMARY]