CREATE TABLE [dbo].[tbl_UPSQuantumViewCapture_ImportHoldingBay] (
    [PKID]                                   INT            IDENTITY (1, 1) NOT NULL,
    [Subscriber ID]                          NVARCHAR (255) NULL,
    [Subscription Name]                      NVARCHAR (255) NULL,
    [Subscription Number]                    NVARCHAR (255) NULL,
    [Query Begin Date]                       NVARCHAR (255) NULL,
    [Query End Date]                         NVARCHAR (255) NULL,
    [Subscription File Name]                 NVARCHAR (255) NULL,
    [File Status]                            NVARCHAR (255) NULL,
    [Record Type]                            NVARCHAR (255) NULL,
    [Shipper Number]                         NVARCHAR (255) NULL,
    [Shipper Name]                           NVARCHAR (255) NULL,
    [Shipper Address Line 1]                 NVARCHAR (255) NULL,
    [Shipper Address Line 2]                 NVARCHAR (255) NULL,
    [Shipper Address Line 3]                 NVARCHAR (255) NULL,
    [Shipper City]                           NVARCHAR (255) NULL,
    [Shipper State/Province]                 NVARCHAR (255) NULL,
    [Shipper Postal Code]                    NVARCHAR (255) NULL,
    [Shipper Country]                        NVARCHAR (255) NULL,
    [Ship To Attention]                      NVARCHAR (255) NULL,
    [Ship To Phone]                          NVARCHAR (255) NULL,
    [Ship To Name]                           NVARCHAR (255) NULL,
    [Ship To Address Line 1]                 NVARCHAR (255) NULL,
    [Ship To Address Line 2]                 NVARCHAR (255) NULL,
    [Ship To Address Line 3]                 NVARCHAR (255) NULL,
    [Ship To City]                           NVARCHAR (255) NULL,
    [Ship To State/Province]                 NVARCHAR (255) NULL,
    [Ship To Postal Code]                    NVARCHAR (255) NULL,
    [Ship To Country]                        NVARCHAR (255) NULL,
    [Ship To Location ID]                    NVARCHAR (255) NULL,
    [Shipment Reference Number Type 1]       NVARCHAR (255) NULL,
    [Shipment Reference Number Value 1]      NVARCHAR (255) NULL,
    [Shipment Reference Number Type 2]       NVARCHAR (255) NULL,
    [Shipment Reference Number Value 2]      NVARCHAR (255) NULL,
    [UPS Service]                            NVARCHAR (255) NULL,
    [Pickup Date]                            NVARCHAR (255) NULL,
    [Scheduled Delivery Date]                NVARCHAR (255) NULL,
    [Scheduled Delivery Time]                NVARCHAR (255) NULL,
    [Document Type]                          NVARCHAR (255) NULL,
    [Package Activity Date]                  NVARCHAR (255) NULL,
    [Package Activity Time]                  NVARCHAR (255) NULL,
    [Package Description]                    NVARCHAR (255) NULL,
    [Package Count]                          NVARCHAR (255) NULL,
    [Package Dimensions Unit of Measurement] NVARCHAR (255) NULL,
    [Length]                                 NVARCHAR (255) NULL,
    [Width]                                  NVARCHAR (255) NULL,
    [Height]                                 NVARCHAR (255) NULL,
    [Package Dimensional Weight]             NVARCHAR (255) NULL,
    [Package Weight]                         NVARCHAR (255) NULL,
    [Oversize Package Type]                  NVARCHAR (255) NULL,
    [Tracking Number]                        NVARCHAR (255) NULL,
    [Package Reference Number Type 1]        NVARCHAR (255) NULL,
    [Package Reference Number Value 1]       NVARCHAR (255) NULL,
    [Package Reference Number Type 2]        NVARCHAR (255) NULL,
    [Package Reference Number Value 2]       NVARCHAR (255) NULL,
    [Package Reference Number Type 3]        NVARCHAR (255) NULL,
    [Package Reference Number Value 3]       NVARCHAR (255) NULL,
    [Package Reference Number Type 4]        NVARCHAR (255) NULL,
    [Package Reference Number Value 4]       NVARCHAR (255) NULL,
    [Package Reference Number Type 5]        NVARCHAR (255) NULL,
    [Package Reference Number Value 5]       NVARCHAR (255) NULL,
    [COD Currency Type]                      NVARCHAR (255) NULL,
    [COD Amount Due]                         NVARCHAR (255) NULL,
    [Declared Value]                         NVARCHAR (255) NULL,
    [Earliest Delivery Time]                 NVARCHAR (255) NULL,
    [Hazardous Materials Type]               NVARCHAR (255) NULL,
    [Hold For Pickup]                        NVARCHAR (255) NULL,
    [Saturday Delivery Indicator]            NVARCHAR (255) NULL,
    [Call Tag ARS Type]                      NVARCHAR (255) NULL,
    [Manufacture Country]                    NVARCHAR (255) NULL,
    [Harmonized Type]                        NVARCHAR (255) NULL,
    [Customs Monetary Value]                 NVARCHAR (255) NULL,
    [Special Instructions]                   NVARCHAR (255) NULL,
    [Shipment Charge Type]                   NVARCHAR (255) NULL,
    [Bill Ship To]                           NVARCHAR (255) NULL,
    [Collect Bill]                           NVARCHAR (255) NULL,
    [UPS Location]                           NVARCHAR (255) NULL,
    [UPS Location State/Province]            NVARCHAR (255) NULL,
    [UPS Location Country]                   NVARCHAR (255) NULL,
    [Updated Ship To Name]                   NVARCHAR (255) NULL,
    [Updated Ship To Street Number]          NVARCHAR (255) NULL,
    [Updated Ship To Street Prefix]          NVARCHAR (255) NULL,
    [Updated Ship To Street Name]            NVARCHAR (255) NULL,
    [Updated Ship To Street Type]            NVARCHAR (255) NULL,
    [Updated Ship To Street Suffix]          NVARCHAR (255) NULL,
    [Updated Ship To Building Name]          NVARCHAR (255) NULL,
    [Updated Ship To Room/Suite/Floor]       NVARCHAR (255) NULL,
    [Updated Ship To Political Division 3]   NVARCHAR (255) NULL,
    [Updated Ship To City]                   NVARCHAR (255) NULL,
    [Updated Ship To State/Province]         NVARCHAR (255) NULL,
    [Updated Ship To Country]                NVARCHAR (255) NULL,
    [Updated Ship To Postal Code]            NVARCHAR (255) NULL,
    [Exception Status Description]           NVARCHAR (255) NULL,
    [Exception Reason Description]           NVARCHAR (500) NULL,
    [Exception Resolution Type]              NVARCHAR (255) NULL,
    [Exception Resolution Description]       NVARCHAR (255) NULL,
    [Rescheduled Delivery Date]              NVARCHAR (255) NULL,
    [Rescheduled Delivery Time]              NVARCHAR (255) NULL,
    [Driver Release]                         NVARCHAR (255) NULL,
    [Delivery Location]                      NVARCHAR (255) NULL,
    [Delivery Name]                          NVARCHAR (255) NULL,
    [Delivery Street Number]                 NVARCHAR (255) NULL,
    [Delivery Street Prefix]                 NVARCHAR (255) NULL,
    [Delivery Street Name]                   NVARCHAR (255) NULL,
    [Delivery Street Type]                   NVARCHAR (255) NULL,
    [Delivery Street Suffix]                 NVARCHAR (255) NULL,
    [Delivery Building Name]                 NVARCHAR (255) NULL,
    [Delivery Room/Suite/Floor]              NVARCHAR (255) NULL,
    [Delivery Political Division 3]          NVARCHAR (255) NULL,
    [Delivery City]                          NVARCHAR (255) NULL,
    [Delivery State/Province]                NVARCHAR (255) NULL,
    [Delivery Country]                       NVARCHAR (255) NULL,
    [Delivery Postal Code]                   NVARCHAR (255) NULL,
    [Residential Address]                    NVARCHAR (255) NULL,
    [Signed For By]                          NVARCHAR (255) NULL,
    [COD Collected Currency Type]            NVARCHAR (255) NULL,
    [COD Amount Collected]                   NVARCHAR (255) NULL,
    [COD Amount Decimal]                     NVARCHAR (255) NULL,
    [Bill To Account Number]                 NVARCHAR (255) NULL,
    [Bill Option]                            NVARCHAR (255) NULL,
    [Exception Reason Code]                  NVARCHAR (255) NULL,
    [Exception Status Code]                  NVARCHAR (255) NULL,
    [Receiving Address Name"]                NVARCHAR (255) NULL,
    [Activity Type]                          NVARCHAR (255) NULL,
    [OrderNo]                                NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([PKID] ASC)
);


GO
