CREATE TABLE [dbo].[test_BC_Round]
(
[PKID] [decimal] (18, 0) NULL,
[orderNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ordersProductsID] [decimal] (18, 0) NULL,
[orderID] [decimal] (18, 0) NULL,
[productQuantity] [decimal] (18, 0) NULL,
[packetValue] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[variableWholeName] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[backName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipsWith] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[resubmit] [bit] NULL,
[shipType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[displayCount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[front_UV] [bit] NULL,
[back_UV] [bit] NULL,
[sortOrder] [decimal] (18, 0) NULL,
[isFlipped] [bit] NULL,
[expressProduction] [bit] NULL,
[simplex] [bit] NULL,
[duplex] [bit] NULL,
[shipCompany] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipFirstName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipLastName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipAddress1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipAddress2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipCity] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipState] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipZip] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipCountry] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipPhone] [decimal] (18, 0) NULL,
[productCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productName] [varchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shortName] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customProductCount] [decimal] (18, 0) NULL,
[customProductCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customProductCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customProductCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customProductCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fasTrakProductCount] [decimal] (18, 0) NULL,
[fasTrakProductCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fasTrakProductCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fasTrakProductCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fasTrakProductCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductCount] [decimal] (18, 0) NULL,
[stockProductQuantity1] [decimal] (18, 0) NULL,
[stockProductCode1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductDescription1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductQuantity2] [decimal] (18, 0) NULL,
[stockProductCode2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductDescription2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductQuantity3] [decimal] (18, 0) NULL,
[stockProductCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductDescription3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductQuantity4] [decimal] (18, 0) NULL,
[stockProductCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductDescription4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductQuantity5] [decimal] (18, 0) NULL,
[stockProductCode5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductDescription5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductQuantity6] [decimal] (18, 0) NULL,
[stockProductCode6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockProductDescription6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]