CREATE TABLE [dbo].[tblKWRD]
(
[orderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderTotal] [money] NULL,
[orderDate] [datetime] NULL,
[orderStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[coordIDUsed] [varchar] (355) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brokerOwnerIDUsed] [varchar] (355) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_firstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_Company] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_street] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_street2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_suburb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_postCode] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billingPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RED Day 101 Ways QuickCard (#KWRD09QC1)] [int] NULL,
[RED Day 101 Ways QuickStix - Case (#KWRD09QS1)] [int] NULL,
[RED Day 101 Ways QuickStix (#KWRD09QS1)] [int] NULL,
[RED Day Balloons (#KWRD09BL1)] [int] NULL,
[RED Day Button (#KWRD09BU1)] [int] NULL,
[RED Day Car/Window Sign (#KWRD09CS1)] [int] NULL,
[RED Day Envelope (#KWRD09EV1)] [int] NULL,
[RED Day Insert (#KWRD09IN1)] [int] NULL,
[RED Day Magnets (#KWRD09MA1)] [int] NULL,
[RED Day Postcard - Jumbo (#KWRD09PJ1)] [int] NULL,
[RED Day Postcard - Regular (#KWRD09PR1)] [int] NULL,
[RED Day Project/Lawn Sign (#KWRD09YS1)] [int] NULL,
[RED Day T-shirt - L (#KWRD09TS3)] [int] NULL,
[RED Day T-shirt - M (#KWRD09TS2)] [int] NULL,
[RED Day T-shirt - S (#KWRD09TS1)] [int] NULL,
[RED Day T-shirt - XL (#KWRD09TS4)] [int] NULL,
[RED Day T-shirt - XXL (#KWRD09TS5)] [int] NULL,
[RED Day T-shirt - XXXL (#KWRD09TS6)] [int] NULL,
[RED Day Water Bottle (#KWRD09WB1)] [int] NULL
) ON [PRIMARY]