CREATE TABLE [dbo].[tblDashboard_Prop_Orders]
(
[PKID] [int] NOT NULL IDENTITY(1, 1),
[orderDate] [datetime] NULL,
[orderID] [int] NULL,
[orderNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calcOrderTotal] [money] NULL,
[calcTransTotal] [money] NULL,
[calcProducts] [money] NULL,
[calcOPPO] [money] NULL,
[calcVouchers] [money] NULL,
[taxAmountAdded] [money] NULL,
[taxDescription] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingAmount] [money] NULL,
[shippingMethod] [int] NULL,
[paymentMethod] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentMethodID] [int] NULL,
[displayPaymentStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modDiff] [bit] NULL CONSTRAINT [DF_tblDashboard_Prop_modDiff] DEFAULT ((0)),
[tblOrders_modified_on] [datetime] NULL,
[readyForProp] [int] NULL CONSTRAINT [DF_tblDashboard_Prop_Orders_readyForProp] DEFAULT ((0)),
[customerID] [int] NULL,
[shipping_company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_firstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_surName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_street2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_suburb] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_state] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_postCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_country] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_firstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_surName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_street2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_suburb] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_state] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_postCode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_country] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billing_phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentMethodRDesc] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentMethodIsCC] [bit] NULL,
[cardNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cardType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentProcessed] [bit] NULL,
[paymentSuccessful] [bit] NULL,
[taxAmountInTotal] [money] NULL,
[feeAmount] [money] NULL,
[specialInstructions] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingDesc] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblDashboard_Prop_Orders] ADD CONSTRAINT [PK_tblDashboard_Prop_Orders] PRIMARY KEY CLUSTERED  ([PKID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NCI_modDiff_readyForProp_INC_orderID] ON [dbo].[tblDashboard_Prop_Orders] ([modDiff], [readyForProp]) INCLUDE ([orderID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_orderDate_ModDiff] ON [dbo].[tblDashboard_Prop_Orders] ([orderDate], [modDiff]) INCLUDE ([orderNo], [tblOrders_modified_on]) ON [PRIMARY]